/* eslint-disable react-hooks/set-state-in-effect */
/* eslint-disable @typescript-eslint/no-explicit-any */
"use client";

import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { supabase } from "@/lib/supabase";
import { CustomerDashboardService, CustomerDriver } from "@/services/customer-dashboard.service";
import CustomerSidebar from "./components/CustomerSidebar";
import CustomerDriversGrid from "./components/CustomerDriversGrid";
import CustomerDriverMonthlyModal from "./components/CustomerDriverMonthlyModal";
import CustomerDashboardSummary from "./components/CustomerDashboardSummary";
import CustomerCompanyCard from "./components/CustomerCompanyCard";
import type { CheckData } from "./types";
import { LogOut, Menu, Wallet, X } from "lucide-react";

const normalizeString = (value: any): string => value == null ? "" : String(value).trim();
const normalizeStatus = (value: any): string => { const s=normalizeString(value).toLowerCase().replace(/\s+/g,""); if(s==="допущен")return "Допущен"; if(["недопущен","отстранен","отстранён"].includes(s))return "Не допущен"; if(s==="ожидание")return "Ожидание"; return normalizeString(value); };
const iso = (d: Date) => `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;

export default function CustomerPage(){
  const router=useRouter(); const today=new Date();
  const [currentUser,setCurrentUser]=useState<any>(null); const [customerId,setCustomerId]=useState<number|null>(null); const [customerName,setCustomerName]=useState("Заказчик"); const [balance,setBalance]=useState<number|null>(null);
  const [drivers,setDrivers]=useState<CustomerDriver[]>([]); const [allChecks,setAllChecks]=useState<CheckData[]>([]); const [transactions,setTransactions]=useState<any[]>([]);
  const [loading,setLoading]=useState(true); const [checksLoading,setChecksLoading]=useState(true); const [search,setSearch]=useState(""); const [mobileMenu,setMobileMenu]=useState(false); const [selectedDriver,setSelectedDriver]=useState<CustomerDriver|null>(null);
  const [selectedDate,setSelectedDate]=useState(today); const [viewDate,setViewDate]=useState(new Date(today.getFullYear(),today.getMonth(),1));

  useEffect(()=>{ const raw=localStorage.getItem("ts_user_session")||localStorage.getItem("currentUser"); if(!raw){router.push("/");return;} let user:any; try{user=JSON.parse(raw)}catch{router.push("/");return;} if(!user||user.role!=="customer"){router.push("/");return;} setCurrentUser(user);
    (async()=>{try{let c:any=null; if(user.customer_id){const r=await supabase.from("customers").select("id,name,type,balance").eq("id",user.customer_id).maybeSingle();if(!r.error&&r.data)c=r.data;} if(!c&&user.id){const r=await supabase.from("customers").select("id,name,type,balance").eq("user_id",user.id).maybeSingle();if(!r.error&&r.data)c=r.data;} if(!c)throw new Error("Не найдена запись заказчика"); const id=Number(c.id); setCustomerId(id); setCustomerName([normalizeString(c.type),normalizeString(c.name)].filter(Boolean).join(" ")||"Заказчик"); setBalance(Number(c.balance||0)); setDrivers(await CustomerDashboardService.getDrivers({...user,customer_id:id})); setTransactions(await CustomerDashboardService.getBalanceTransactions(id));}catch(e){console.error(e)}finally{setLoading(false)}})();
  },[router]);

  useEffect(()=>{if(!drivers.length){setAllChecks([]);setChecksLoading(false);return;} const load=async()=>{setChecksLoading(true);try{const data=await CustomerDashboardService.getInspections(drivers.map(d=>d.id));setAllChecks(data.map(x=>{const d=x.requested_at?new Date(x.requested_at):new Date();return {...x,overall_status:normalizeStatus(x.overall_status),medical_status:normalizeStatus(x.medical_status),mechanic_status:normalizeStatus(x.mechanic_status),dateISO:iso(d),time:d.toTimeString().slice(0,5)} as CheckData}))}finally{setChecksLoading(false)}};load(); const ch=supabase.channel("customer-inspections-realtime").on("postgres_changes",{event:"*",schema:"public",table:"inspections"},load).subscribe();return()=>{supabase.removeChannel(ch)}},[drivers]);

  useEffect(()=>{if(!customerId)return; let active=true; const load=async()=>{try{const r=await supabase.from("customers").select("balance").eq("id",customerId).maybeSingle();if(!r.error&&r.data&&active)setBalance(Number(r.data.balance||0));const history=await CustomerDashboardService.getBalanceTransactions(customerId);if(active)setTransactions(history);}catch(e){console.error("Не удалось обновить баланс заказчика",e)}};load(); const ch=supabase.channel(`customer-balance-realtime-${customerId}`).on("postgres_changes",{event:"*",schema:"public",table:"customer_balance_transactions",filter:`customer_id=eq.${customerId}`},()=>{load()}).on("postgres_changes",{event:"*",schema:"public",table:"customers",filter:`id=eq.${customerId}`},()=>{load()}).subscribe(); const timer=window.setInterval(load,5000); return()=>{active=false;window.clearInterval(timer);supabase.removeChannel(ch)}},[customerId]);

  const selectedISO=iso(selectedDate); const checks=useMemo(()=>allChecks.filter(c=>c.dateISO===selectedISO),[allChecks,selectedISO]); const prefix=`${viewDate.getFullYear()}-${String(viewDate.getMonth()+1).padStart(2,"0")}`; const monthChecks=useMemo(()=>allChecks.filter(c=>c.dateISO.startsWith(prefix)),[allChecks,prefix]);
  const selectedDriverChecks=selectedDriver?monthChecks.filter(c=>c.driver_id===selectedDriver.id):[]; const selectedDriverStats={approved:selectedDriverChecks.filter(c=>c.overall_status==="Допущен").length,rejected:selectedDriverChecks.filter(c=>c.overall_status==="Не допущен").length,pending:selectedDriverChecks.filter(c=>c.overall_status==="Ожидание").length};
  const stats={approved:checks.filter(c=>c.overall_status==="Допущен").length,rejected:checks.filter(c=>c.overall_status==="Не допущен").length,pending:checks.filter(c=>c.overall_status==="Ожидание").length};
  const monthLabel=new Intl.DateTimeFormat("ru-RU",{month:"long",year:"numeric"}).format(viewDate); const formatted=selectedDate.toLocaleDateString("ru-RU",{day:"numeric",month:"long",year:"numeric"});
  const logout=()=>{localStorage.removeItem("currentUser");localStorage.removeItem("ts_user_session");router.push("/")};
  if(loading)return <div className="flex min-h-screen items-center justify-center bg-slate-950 text-white"><div className="text-center"><div className="mx-auto mb-4 h-9 w-9 animate-spin rounded-full border-2 border-white/20 border-t-white"/><p className="text-sm text-white/60">Загружаем личный кабинет...</p></div></div>;

  return <div className="min-h-screen bg-[#f5f7fa] text-slate-900">
   <header className="sticky top-0 z-30 border-b border-white/10 bg-[#062a3a] text-white shadow-lg"><div className="mx-auto flex min-h-[72px] max-w-[1500px] items-center justify-between gap-4 px-4 py-3 sm:px-6 lg:px-8"><div className="flex min-w-0 items-center gap-3"><button onClick={()=>setMobileMenu(true)} className="rounded-xl p-2 hover:bg-white/10 md:hidden"><Menu size={21}/></button><div className="flex h-10 w-10 shrink-0 items-center justify-center overflow-hidden rounded-xl bg-white"><img src="/logo.png" alt="Транспортный Щит" className="h-full w-full object-contain p-1"/></div><div className="min-w-0"><div className="truncate text-sm font-bold sm:text-base">Транспортный Щит</div><div className="truncate text-[10px] uppercase tracking-[.18em] text-white/50">Личный кабинет заказчика</div></div></div><div className="flex min-w-0 items-center gap-3 sm:gap-5"><div className="hidden min-w-0 text-right sm:block"><div className="max-w-[240px] truncate text-sm font-semibold">{customerName}</div><div className="text-xs text-white/50">{currentUser?.login||"Аккаунт заказчика"}</div></div><div className="hidden items-center gap-4 lg:flex"><div className="text-right"><div className="text-[10px] uppercase tracking-wider text-white/40">Водителей</div><div className="text-sm font-semibold">{drivers.length}</div></div><div className="h-8 w-px bg-white/10"/><div className="text-right"><div className="text-[10px] uppercase tracking-wider text-white/40">Осмотров за месяц</div><div className="text-sm font-semibold">{monthChecks.length}</div></div></div><div className="flex items-center gap-2 rounded-xl bg-emerald-400/10 px-3 py-2"><Wallet size={17} className="text-emerald-300"/><div><div className="text-[10px] uppercase tracking-wider text-white/40">Баланс</div><div className="text-sm font-bold">{balance==null?"—":`${balance.toFixed(2)} BYN`}</div></div></div><button onClick={logout} className="rounded-xl p-2.5 text-white/70 hover:bg-white/10 hover:text-white"><LogOut size={18}/></button></div></div></header>
   {mobileMenu&&<div className="fixed inset-0 z-50 bg-slate-950/40 md:hidden" onClick={()=>setMobileMenu(false)}><aside className="h-full w-[300px] bg-white p-5" onClick={e=>e.stopPropagation()}><div className="mb-8 flex justify-between font-bold">Профиль заказчика<button onClick={()=>setMobileMenu(false)}><X size={20}/></button></div><div className="rounded-2xl bg-slate-50 p-4"><div className="text-xs text-slate-400">Компания</div><div className="mt-1 font-bold">{customerName}</div><div className="mt-1 text-xs text-slate-400">{currentUser?.login||"Аккаунт заказчика"}</div></div><div className="mt-4 rounded-2xl bg-emerald-50 p-4"><div className="text-xs text-emerald-600">Баланс</div><div className="mt-1 text-xl font-bold text-emerald-700">{balance==null?"—":`${balance.toFixed(2)} BYN`}</div></div><button onClick={logout} className="mt-6 flex w-full gap-3 rounded-xl p-3 font-semibold text-red-600 hover:bg-red-50"><LogOut size={18}/>Выйти</button></aside></div>}
   <main className="mx-auto max-w-[1500px] px-4 py-6 sm:px-6 lg:px-8 lg:py-8">
    <CustomerDashboardSummary drivers={drivers} checks={checks} stats={stats} formatted={formatted}/>
    <section className="mt-6 grid gap-6 xl:grid-cols-[330px_minmax(0,1fr)]"><CustomerSidebar viewDate={viewDate} today={today} monthLabel={monthLabel} selectedDate={selectedDate} transactions={transactions} setViewDate={setViewDate} setSelectedDate={setSelectedDate}/><CustomerDriversGrid drivers={drivers} checks={checks} checksLoading={checksLoading} search={search} formatted={formatted} setSearch={setSearch} onSelectDriver={setSelectedDriver}/></section>
    <CustomerCompanyCard customerName={customerName} login={currentUser?.login} driversCount={drivers.length}/>
   </main>
   {selectedDriver&&<CustomerDriverMonthlyModal selectedDriver={selectedDriver} selectedDriverChecks={selectedDriverChecks} monthLabel={monthLabel} stats={selectedDriverStats} onClose={()=>setSelectedDriver(null)}/>} 
  </div>;
}