/* eslint-disable react-hooks/set-state-in-effect */
/* eslint-disable @typescript-eslint/no-explicit-any */
"use client";

import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { supabase } from "@/lib/supabase";
import { CustomerDashboardService, CustomerBalanceTransaction, CustomerDriver, CustomerInspection } from "@/services/customer-dashboard.service";
import { Activity, AlertTriangle, Building2, Car, CheckCircle2, ChevronLeft, ChevronRight, Clock3, FileCheck2, LogOut, Menu, Search, Users, Wallet, X, XCircle, ArrowDownLeft, ArrowUpRight } from "lucide-react";

interface CheckData extends CustomerInspection { dateISO: string; time: string; }
const normalizeString = (value: any): string => value == null ? "" : String(value).trim();
const normalizeStatus = (value: any): string => { const s=normalizeString(value).toLowerCase().replace(/\s+/g,""); if(s==="допущен")return "Допущен"; if(["недопущен","отстранен","отстранён"].includes(s))return "Не допущен"; if(s==="ожидание")return "Ожидание"; return normalizeString(value); };
const iso = (d: Date) => `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;
const tone=(s:string)=>s==="Допущен"?"text-emerald-700 bg-emerald-50 border-emerald-200":s==="Не допущен"?"text-red-700 bg-red-50 border-red-200":"text-amber-700 bg-amber-50 border-amber-200";
const dot=(s:string)=>s==="Допущен"?"bg-emerald-500":s==="Не допущен"?"bg-red-500":"bg-amber-500";

export default function CustomerPage(){
 const router=useRouter(); const today=new Date();
 const [currentUser,setCurrentUser]=useState<any>(null); const [customerId,setCustomerId]=useState<number|null>(null); const [customerName,setCustomerName]=useState("Заказчик"); const [balance,setBalance]=useState<number|null>(null);
 const [drivers,setDrivers]=useState<CustomerDriver[]>([]); const [allChecks,setAllChecks]=useState<CheckData[]>([]); const [transactions,setTransactions]=useState<CustomerBalanceTransaction[]>([]);
 const [loading,setLoading]=useState(true); const [checksLoading,setChecksLoading]=useState(true); const [search,setSearch]=useState(""); const [mobileMenu,setMobileMenu]=useState(false); const [selectedDriver,setSelectedDriver]=useState<CustomerDriver|null>(null);
 const [selectedDate,setSelectedDate]=useState(today); const [viewDate,setViewDate]=useState(new Date(today.getFullYear(),today.getMonth(),1));

 useEffect(()=>{ const raw=localStorage.getItem("ts_user_session")||localStorage.getItem("currentUser"); if(!raw){router.push("/");return;} let user:any; try{user=JSON.parse(raw)}catch{router.push("/");return;} if(!user||user.role!=="customer"){router.push("/");return;} setCurrentUser(user);
  (async()=>{try{let c:any=null; if(user.customer_id){const r=await supabase.from("customers").select("id,name,type,balance").eq("id",user.customer_id).maybeSingle();if(!r.error&&r.data)c=r.data;} if(!c&&user.id){const r=await supabase.from("customers").select("id,name,type,balance").eq("user_id",user.id).maybeSingle();if(!r.error&&r.data)c=r.data;} if(!c)throw new Error("Не найдена запись заказчика"); const id=Number(c.id); setCustomerId(id); setCustomerName([normalizeString(c.type),normalizeString(c.name)].filter(Boolean).join(" ")||"Заказчик"); setBalance(Number(c.balance||0)); setDrivers(await CustomerDashboardService.getDrivers({...user,customer_id:id})); setTransactions(await CustomerDashboardService.getBalanceTransactions(id));}catch(e){console.error(e)}finally{setLoading(false)}})();
 },[router]);

 useEffect(()=>{if(!drivers.length){setAllChecks([]);setChecksLoading(false);return;} const load=async()=>{setChecksLoading(true);try{const data=await CustomerDashboardService.getInspections(drivers.map(d=>d.id));setAllChecks(data.map(x=>{const d=x.requested_at?new Date(x.requested_at):new Date();return {...x,overall_status:normalizeStatus(x.overall_status),medical_status:normalizeStatus(x.medical_status),mechanic_status:normalizeStatus(x.mechanic_status),dateISO:iso(d),time:d.toTimeString().slice(0,5)} as CheckData}))}finally{setChecksLoading(false)}};load(); const ch=supabase.channel("customer-inspections-realtime").on("postgres_changes",{event:"*",schema:"public",table:"inspections"},load).subscribe();return()=>{supabase.removeChannel(ch)}},[drivers]);
 useEffect(()=>{if(!customerId)return; const load=async()=>{const r=await supabase.from("customers").select("balance").eq("id",customerId).maybeSingle();if(!r.error&&r.data)setBalance(Number(r.data.balance||0));setTransactions(await CustomerDashboardService.getBalanceTransactions(customerId));};load();const ch=supabase.channel("customer-balance-realtime").on("postgres_changes",{event:"*",schema:"public",table:"customer_balance_transactions",filter:`customer_id=eq.${customerId}`},load).subscribe();return()=>{supabase.removeChannel(ch)}},[customerId]);

 const selectedISO=iso(selectedDate); const checks=useMemo(()=>allChecks.filter(c=>c.dateISO===selectedISO),[allChecks,selectedISO]); const prefix=`${viewDate.getFullYear()}-${String(viewDate.getMonth()+1).padStart(2,"0")}`; const monthChecks=useMemo(()=>allChecks.filter(c=>c.dateISO.startsWith(prefix)),[allChecks,prefix]); const filtered=useMemo(()=>{const q=search.toLowerCase().trim();return q?drivers.filter(d=>`${d.name} ${d.number} ${d.car_brand} ${d.car_number}`.toLowerCase().includes(q)):drivers},[drivers,search]);
 const selectedDriverChecks=selectedDriver?monthChecks.filter(c=>c.driver_id===selectedDriver.id):[]; const selectedDriverStats={approved:selectedDriverChecks.filter(c=>c.overall_status==="Допущен").length,rejected:selectedDriverChecks.filter(c=>c.overall_status==="Не допущен").length,pending:selectedDriverChecks.filter(c=>c.overall_status==="Ожидание").length};
 const stats={approved:checks.filter(c=>c.overall_status==="Допущен").length,rejected:checks.filter(c=>c.overall_status==="Не допущен").length,pending:checks.filter(c=>c.overall_status==="Ожидание").length};
 const monthLabel=new Intl.DateTimeFormat("ru-RU",{month:"long",year:"numeric"}).format(viewDate); const formatted=selectedDate.toLocaleDateString("ru-RU",{day:"numeric",month:"long",year:"numeric"}); const days=Array.from({length:new Date(viewDate.getFullYear(),viewDate.getMonth()+1,0).getDate()},(_,i)=>i+1).filter(d=>new Date(viewDate.getFullYear(),viewDate.getMonth(),d)<=new Date(today.getFullYear(),today.getMonth(),today.getDate()));
 const logout=()=>{localStorage.removeItem("currentUser");localStorage.removeItem("ts_user_session");router.push("/")};
 if(loading)return <div className="flex min-h-screen items-center justify-center bg-slate-950 text-white"><div className="text-center"><div className="mx-auto mb-4 h-9 w-9 animate-spin rounded-full border-2 border-white/20 border-t-white"/><p className="text-sm text-white/60">Загружаем личный кабинет...</p></div></div>;

 return <div className="min-h-screen bg-[#f5f7fa] text-slate-900">
  <header className="sticky top-0 z-30 border-b border-white/10 bg-[#062a3a] text-white shadow-lg"><div className="mx-auto flex h-[72px] max-w-[1500px] items-center justify-between px-4 sm:px-6 lg:px-8"><div className="flex min-w-0 items-center gap-3"><button onClick={()=>setMobileMenu(true)} className="rounded-xl p-2 hover:bg-white/10 md:hidden"><Menu size={21}/></button><div className="flex h-10 w-10 shrink-0 items-center justify-center overflow-hidden rounded-xl bg-white"><img src="/logo.png" alt="Транспортный Щит" className="h-full w-full object-contain p-1"/></div><div><div className="text-sm font-bold">Транспортный Щит</div><div className="text-[10px] uppercase tracking-[.18em] text-white/50">Личный кабинет заказчика</div></div></div><div className="flex items-center gap-3"><div className="hidden text-right sm:block"><div className="max-w-[280px] truncate text-sm font-semibold">{customerName}</div><div className="text-xs text-white/50">{currentUser?.login||"Аккаунт заказчика"}</div></div><button onClick={logout} className="rounded-xl p-2.5 text-white/70 hover:bg-white/10 hover:text-white"><LogOut size={18}/></button></div></div></header>
  {mobileMenu&&<div className="fixed inset-0 z-50 bg-slate-950/40 md:hidden" onClick={()=>setMobileMenu(false)}><aside className="h-full w-[300px] bg-white p-5" onClick={e=>e.stopPropagation()}><div className="mb-8 flex justify-between font-bold">Профиль заказчика<button onClick={()=>setMobileMenu(false)}><X size={20}/></button></div><div className="rounded-2xl bg-slate-50 p-4"><div className="text-xs text-slate-400">Компания</div><div className="mt-1 font-bold">{customerName}</div></div><button onClick={logout} className="mt-6 flex w-full gap-3 rounded-xl p-3 font-semibold text-red-600 hover:bg-red-50"><LogOut size={18}/>Выйти</button></aside></div>}
  <main className="mx-auto max-w-[1500px] px-4 py-6 sm:px-6 lg:px-8 lg:py-8">
   <section className="overflow-hidden rounded-3xl bg-gradient-to-br from-[#07364a] via-[#062a3a] to-[#041d29] p-6 text-white shadow-xl sm:p-8"><div className="flex flex-col justify-between gap-8 lg:flex-row lg:items-end"><div><div className="mb-3 inline-flex items-center gap-2 rounded-full bg-white/10 px-3 py-1.5 text-xs font-semibold"><Activity size={14}/>Мониторинг транспорта</div><h1 className="text-2xl font-bold sm:text-3xl lg:text-4xl">Добро пожаловать, {customerName}</h1><p className="mt-2 text-sm text-white/60 sm:text-base">Контролируйте водителей, прохождения медосмотра и технического осмотра в одном месте.</p></div><div className="grid grid-cols-2 gap-3 sm:grid-cols-3"><div className="rounded-2xl bg-white/10 p-4"><Users size={18} className="mb-3 text-white/60"/><div className="text-2xl font-bold">{drivers.length}</div><div className="text-xs text-white/50">Водителей</div></div><div className="rounded-2xl bg-white/10 p-4"><FileCheck2 size={18} className="mb-3 text-white/60"/><div className="text-2xl font-bold">{monthChecks.length}</div><div className="text-xs text-white/50">Осмотров за месяц</div></div><div className="col-span-2 rounded-2xl bg-emerald-400/10 p-4 sm:col-span-1"><Wallet size={18} className="mb-3 text-emerald-300"/><div className="text-2xl font-bold">{balance==null?"—":`${balance.toFixed(2)} BYN`}</div><div className="text-xs text-white/50">Баланс</div></div></div></div></section>
   <section className="mt-6 grid grid-cols-2 gap-3 lg:grid-cols-4">{[["Допущено",stats.approved,CheckCircle2,"text-emerald-500"],["Не допущено",stats.rejected,XCircle,"text-red-500"],["Ожидание",stats.pending,Clock3,"text-amber-500"],["Без осмотра",Math.max(0,drivers.length-new Set(checks.map(c=>c.driver_id)).size),AlertTriangle,"text-slate-400"]].map(([l,v,I,c])=><div key={String(l)} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex justify-between"><span className="text-xs font-semibold uppercase tracking-wider text-slate-400">{l}</span><I className={String(c)} size={20}/></div><div className="mt-3 text-3xl font-bold">{v as number}</div><div className="mt-1 text-xs text-slate-500">за {formatted}</div></div>)}</section>
   <section className="mt-6 grid gap-6 xl:grid-cols-[330px_minmax(0,1fr)]"><div><div className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><button onClick={()=>setViewDate(new Date(viewDate.getFullYear(),viewDate.getMonth()-1,1))} className="rounded-xl p-2 hover:bg-slate-100"><ChevronLeft size={18}/></button><div className="text-sm font-bold capitalize">{monthLabel}</div><button onClick={()=>setViewDate(new Date(viewDate.getFullYear(),viewDate.getMonth()+1,1))} disabled={viewDate.getFullYear()===today.getFullYear()&&viewDate.getMonth()===today.getMonth()} className="rounded-xl p-2 disabled:opacity-30"><ChevronRight size={18}/></button></div><div className="mt-5 grid grid-cols-7 gap-1 text-center text-[10px] font-bold uppercase text-slate-400">{['Пн','Вт','Ср','Чт','Пт','Сб','Вс'].map(d=><div key={d}>{d}</div>)}</div><div className="mt-2 grid grid-cols-7 gap-1">{Array.from({length:(new Date(viewDate.getFullYear(),viewDate.getMonth(),1).getDay()+6)%7}).map((_,i)=><div key={i}/>)}{days.map(d=>{const date=new Date(viewDate.getFullYear(),viewDate.getMonth(),d);const selected=date.toDateString()===selectedDate.toDateString();return <button key={d} onClick={()=>setSelectedDate(date)} className={`relative h-9 rounded-lg text-xs font-semibold ${selected?'bg-[#0b6078] text-white':'hover:bg-slate-100'}`}>{d}</button>})}</div><button onClick={()=>{setSelectedDate(today);setViewDate(new Date(today.getFullYear(),today.getMonth(),1))}} className="mt-4 w-full rounded-xl bg-slate-50 py-2 text-xs font-semibold text-slate-600">Сегодня</button></div>
    <div className="mt-4 rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><div><div className="text-xs font-bold uppercase tracking-wider text-slate-400">Баланс</div><h3 className="mt-1 text-lg font-bold">История операций</h3></div><Wallet size={20} className="text-[#0b6078]"/></div><div className="mt-4 max-h-[420px] space-y-2 overflow-y-auto pr-1">{transactions.length===0?<div className="rounded-2xl bg-slate-50 p-6 text-center text-sm text-slate-400">Операций пока нет</div>:transactions.map(t=>{const positive=t.amount>0;const driver=t.driver_name||t.driver_id;return <div key={t.id} className="rounded-2xl border border-slate-100 p-3"><div className="flex items-start gap-3"><div className={`mt-0.5 rounded-xl p-2 ${positive?'bg-emerald-50 text-emerald-600':'bg-red-50 text-red-600'}`}>{positive?<ArrowDownLeft size={16}/>:<ArrowUpRight size={16}/>}</div><div className="min-w-0 flex-1"><div className="flex items-center justify-between gap-2"><span className="text-sm font-bold">{positive?"Пополнение":"Списание"}</span><span className={`text-sm font-bold ${positive?'text-emerald-600':'text-red-600'}`}>{positive?'+':''}{t.amount.toFixed(2)} BYN</span></div><div className="mt-1 text-xs text-slate-500">{t.description||"Операция по балансу"}</div>{!positive&&driver&&<div className="mt-1 truncate text-xs font-medium text-slate-600">Водитель: {driver}</div>}<div className="mt-1 text-[10px] text-slate-400">{new Date(t.created_at).toLocaleString("ru-RU",{day:"2-digit",month:"2-digit",year:"numeric",hour:"2-digit",minute:"2-digit"})}{t.balance_after!=null?` · Баланс ${t.balance_after.toFixed(2)} BYN`:''}</div></div></div></div>})}</div></div></div>
    <div><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div><h2 className="text-xl font-bold">Водители</h2><p className="mt-1 text-sm text-slate-500">Результаты осмотров на {formatted}</p></div><div className="relative w-full sm:w-[280px]"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" size={17}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Поиск водителя или авто..." className="w-full rounded-xl border border-slate-200 bg-white py-2.5 pl-9 pr-3 text-sm outline-none focus:border-[#0b6078]"/></div></div>{checksLoading?<div className="mt-5 rounded-2xl border border-slate-200 bg-white p-10 text-center text-sm text-slate-500">Загружаем результаты...</div>:<div className="mt-5 grid gap-3 md:grid-cols-2 2xl:grid-cols-3">{filtered.map(d=>{const ds=checks.filter(c=>c.driver_id===d.id);const last=ds[0];return <button type="button" key={d.id} onClick={()=>setSelectedDriver(d)} className="w-full cursor-pointer rounded-2xl border border-slate-200 bg-white p-5 text-left shadow-sm transition hover:-translate-y-0.5 hover:border-[#0b6078]/30 hover:shadow-md"><div className="flex justify-between gap-3"><div className="min-w-0"><div className="flex items-center gap-2 text-xs font-bold text-slate-400"><Car size={14}/>{d.car_brand||'Автомобиль'}{d.car_number?` • ${d.car_number}`:''}</div><div className="mt-2 truncate text-base font-bold">{d.name||'Без имени'}</div>{d.number&&<div className="mt-1 text-xs text-slate-400">Табельный № {d.number}</div>}</div><div className={`shrink-0 rounded-full border px-2.5 py-1 text-[10px] font-bold ${last?tone(last.overall_status):'border-slate-200 bg-slate-50 text-slate-400'}`}>{last?last.overall_status:'Нет осмотра'}</div></div>{last?<div className="mt-5 space-y-2 border-t border-slate-100 pt-4 text-xs"><div className="flex justify-between"><span className="text-slate-500">Медик</span><span className="flex items-center gap-2 font-semibold"><span className={`h-2 w-2 rounded-full ${dot(last.medical_status)}`}/>{last.medical_status}</span></div><div className="flex justify-between"><span className="text-slate-500">Механик</span><span className="flex items-center gap-2 font-semibold"><span className={`h-2 w-2 rounded-full ${dot(last.mechanic_status)}`}/>{last.mechanic_status}</span></div><div className="flex justify-between text-slate-400"><span>Время</span><span>{last.time}</span></div></div>:<div className="mt-5 border-t border-slate-100 pt-4 text-xs text-slate-400">За выбранную дату осмотр не зарегистрирован.</div>}</button>})}</div>}</div></section>
   <section className="mt-6 grid gap-6 lg:grid-cols-2"><div className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div className="text-xs font-bold uppercase tracking-wider text-slate-400">Сводка</div><h3 className="mt-1 text-lg font-bold capitalize">{monthLabel}</h3><div className="mt-6 grid grid-cols-2 gap-3 sm:grid-cols-4">{[["Допущено",monthChecks.filter(c=>c.overall_status==="Допущен").length,"text-emerald-600"],["Не допущено",monthChecks.filter(c=>c.overall_status==="Не допущен").length,"text-red-600"],["Ожидание",monthChecks.filter(c=>c.overall_status==="Ожидание").length,"text-amber-600"],["Без осмотра",Math.max(0,drivers.length-new Set(monthChecks.map(c=>c.driver_id)).size),"text-slate-500"]].map(([l,v,c])=><div key={String(l)} className="rounded-2xl bg-slate-50 p-4"><div className={`text-2xl font-bold ${c}`}>{v}</div><div className="mt-1 text-[11px] text-slate-500">{l}</div></div>)}</div></div><div className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center gap-3"><div className="rounded-xl bg-slate-100 p-2.5"><Building2 size={19}/></div><div><div className="text-xs font-bold uppercase tracking-wider text-slate-400">Компания</div><h3 className="mt-1 text-lg font-bold">{customerName}</h3></div></div><div className="mt-6 grid gap-3 sm:grid-cols-2"><div className="rounded-2xl border border-slate-100 p-4"><div className="text-xs text-slate-400">Логин</div><div className="mt-1 font-semibold">{currentUser?.login||'—'}</div></div><div className="rounded-2xl border border-slate-100 p-4"><div className="text-xs text-slate-400">Водителей</div><div className="mt-1 font-semibold">{drivers.length}</div></div></div></div></section>
  </main>
  {selectedDriver&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/50 p-4 backdrop-blur-sm" onClick={()=>setSelectedDriver(null)}><div className="max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-3xl bg-white shadow-2xl" onClick={e=>e.stopPropagation()}><div className="sticky top-0 flex items-start justify-between border-b border-slate-100 bg-white p-6"><div><div className="text-xs font-bold uppercase tracking-wider text-slate-400">Сводка за месяц</div><h2 className="mt-1 text-2xl font-bold">{selectedDriver.name||'Без имени'}</h2><div className="mt-1 text-sm text-slate-500">{selectedDriver.car_brand||'Автомобиль'}{selectedDriver.car_number?` • ${selectedDriver.car_number}`:''} · {monthLabel}</div></div><button onClick={()=>setSelectedDriver(null)} className="rounded-xl p-2 text-slate-400 hover:bg-slate-100"><X size={20}/></button></div><div className="p-6"><div className="grid grid-cols-3 gap-3"><div className="rounded-2xl bg-emerald-50 p-4"><div className="text-2xl font-bold text-emerald-700">{selectedDriverStats.approved}</div><div className="text-xs text-emerald-700/70">Допущен</div></div><div className="rounded-2xl bg-red-50 p-4"><div className="text-2xl font-bold text-red-700">{selectedDriverStats.rejected}</div><div className="text-xs text-red-700/70">Не допущен</div></div><div className="rounded-2xl bg-amber-50 p-4"><div className="text-2xl font-bold text-amber-700">{selectedDriverStats.pending}</div><div className="text-xs text-amber-700/70">Ожидание</div></div></div><div className="mt-6 space-y-3">{selectedDriverChecks.map(c=><div key={c.id} className="rounded-2xl border border-slate-200 p-4"><div className="flex justify-between"><div><div className="font-semibold">{new Date(c.requested_at).toLocaleDateString('ru-RU')}</div><div className="text-xs text-slate-400">{c.time}</div></div><div className={`rounded-full border px-3 py-1 text-xs font-bold ${tone(c.overall_status)}`}>{c.overall_status}</div></div><div className="mt-3 grid grid-cols-2 gap-2 text-xs"><div className="rounded-xl bg-slate-50 p-3">Медик: <b>{c.medical_status}</b></div><div className="rounded-xl bg-slate-50 p-3">Механик: <b>{c.mechanic_status}</b></div></div></div>)}</div></div></div></div>}
 </div>
}
