/* eslint-disable @typescript-eslint/no-explicit-any */
import { supabase } from "@/lib/supabase";
import { Inspection } from "../types/database.types";
export const PAGE_SIZE = 30;
const MIN_SYSTOLIC=90,MAX_SYSTOLIC=140,MIN_DIASTOLIC=60,MAX_DIASTOLIC=90;
function isBloodPressureWithinNormalRange(s:number|null,d:number|null){return s!=null&&d!=null&&s>=MIN_SYSTOLIC&&s<=MAX_SYSTOLIC&&d>=MIN_DIASTOLIC&&d<=MAX_DIASTOLIC}
interface Names{medic_surname:string;mechanic_surname:string}
function getCurrentUserId(): number | null {
  if (typeof window === "undefined") return null;
  try { const raw=localStorage.getItem("ts_user_session")||localStorage.getItem("currentUser"); if(!raw)return null; const session=JSON.parse(raw) as {id?:number|string}; const id=Number(session.id); return Number.isFinite(id)?id:null; } catch { return null; }
}
export const formatInspectionItem=(item:any,names:Names={medic_surname:"",mechanic_surname:""}):Inspection=>{let medicalTimeFormatted="—",mechanicTimeFormatted="—",generalTimeFormatted="—";if(item.medical_date){const d=new Date(item.medical_date);medicalTimeFormatted=d.toLocaleDateString("ru-RU",{day:"2-digit",month:"2-digit"})+", "+d.toLocaleTimeString("ru-RU",{hour:"2-digit",minute:"2-digit"})}if(item.mechanic_date){const d=new Date(item.mechanic_date);mechanicTimeFormatted=d.toLocaleDateString("ru-RU",{day:"2-digit",month:"2-digit"})+", "+d.toLocaleTimeString("ru-RU",{hour:"2-digit",minute:"2-digit"})}const targetDateStr=item.requested_at||item.created_at;if(targetDateStr){const d=new Date(targetDateStr);generalTimeFormatted=d.toLocaleDateString("ru-RU",{day:"2-digit",month:"2-digit",year:"numeric"})+", "+d.toLocaleTimeString("ru-RU",{hour:"2-digit",minute:"2-digit"})}const medicalExaminer=item.medical_examiner_name||item.medical_examiner?.login||item.medical_examiner?.name||names.medic_surname||"Медик";const mechanicExaminer=item.mechanic_examiner_name||item.mechanic_examiner?.login||item.mechanic_examiner?.name||names.mechanic_surname||"Механик";return{docId:String(item.id),id:item.drivers?.driver_id?`${item.drivers.driver_id}_${item.id}`:item.id,driver:item.drivers?.name||"Не указан",customer:item.drivers?.customers?.name||"Не указан",date:generalTimeFormatted,dateISO:targetDateStr,status:item.overall_status||"Ожидание",documents:{license:item.drivers?.license_number||"—",licenseExpires:item.drivers?.license_expiry||"—",medical:item.drivers?.medical_expiry||"—",inspection:item.drivers?.tech_inspection_expiry||"—"},car:{number:item.drivers?.car_number||"—",brand:item.drivers?.car_brand||"—"},medic:medicalExaminer,medicTime:medicalTimeFormatted,medicStatus:item.medical_status||"Ожидание",alcohol:item.breathalyzer_value??null,bloodPressureSystolic:item.blood_pressure_systolic??null,bloodPressureDiastolic:item.blood_pressure_diastolic??null,drugIntoxication:Boolean(item.drug_intoxication),mechanic:mechanicExaminer,mechanicTime:mechanicTimeFormatted,mechanicStatus:item.mechanic_status||"Ожидание",mechanicReasons:item.mechanic_issues||[],medicalExaminerId:item.medical_examiner_id??null,mechanicExaminerId:item.mechanic_examiner_id??null}}
async function getNames():Promise<Names>{const{data}=await supabase.from("system_settings").select("medic_last_name,mechanic_last_name").eq("id",1).maybeSingle();return{medic_surname:data?.medic_last_name||"",mechanic_surname:data?.mechanic_last_name||""}}
async function getConfiguredNames():Promise<Names>{return getNames()}
interface FetchInspectionsParams{currentPage:number;statusFilter:string;startDateFilter:string;endDateFilter:string;search:string}
const baseSelect=`*, drivers!inspections_driver_id_fkey (id, driver_id, name, license_number, license_expiry, medical_expiry, tech_inspection_expiry, car_brand, car_number, customers ( name )), medical_examiner:users!inspections_medical_examiner_id_fkey (id, login), mechanic_examiner:users!inspections_mechanic_examiner_id_fkey (id, login)`;
export async function fetchInspectionsData({currentPage,statusFilter,startDateFilter,endDateFilter,search}:FetchInspectionsParams){const from=(currentPage-1)*PAGE_SIZE,to=from+PAGE_SIZE-1;let startIso:string|null=null,endIso:string|null=null;if(startDateFilter){const[y,m,d]=startDateFilter.split("-").map(Number);startIso=new Date(y,m-1,d,0,0,0).toISOString()}if(endDateFilter){const[y,m,d]=endDateFilter.split("-").map(Number);endIso=new Date(y,m-1,d+1,0,0,0,0).toISOString()}const applySearchFilter=(query:any,term:string)=>{if(!term)return query;const clean=term.trim();return query.not('drivers','is',null).or(`name.ilike.%${clean}%,car_number.ilike.%${clean}%,driver_id.ilike.%${clean}%,license_number.ilike.%${clean}%`,{foreignTable:"drivers"})};let query=supabase.from("inspections").select(baseSelect,{count:"exact"});if(["Допущен","Не допущен","Явиться"].includes(statusFilter)){query=query.eq("overall_status",statusFilter);if(startIso)query=query.gte("completed_at",startIso);if(endIso)query=query.lt("completed_at",endIso)}else if(statusFilter==="Ожидание"){query=query.eq("overall_status","Ожидание");if(startIso)query=query.gte("requested_at",startIso);if(endIso)query=query.lt("requested_at",endIso)}else{if(startIso&&endIso)query=query.or(`and(completed_at.gte."${startIso}",completed_at.lt."${endIso}"),and(overall_status.eq.Ожидание,requested_at.gte."${startIso}",requested_at.lt."${endIso}")`);else if(startIso)query=query.or(`completed_at.gte."${startIso}",and(overall_status.eq.Ожидание,requested_at.gte."${startIso}")`);else if(endIso)query=query.or(`completed_at.lt."${endIso}",and(overall_status.eq.Ожидание,requested_at.lt."${endIso}")`)}query=applySearchFilter(query,search).order("completed_at",{ascending:false,nullsFirst:true}).order("created_at",{ascending:false}).range(from,to);const{data,error,count}=await query;if(error)return{formatted:[],totalCount:count??0};const names=await getNames();return{formatted:(data||[]).map(x=>formatInspectionItem(x,names)),totalCount:count??0}}
export async function fetchStatusCounts({startDateFilter,endDateFilter,search}:{startDateFilter:string;endDateFilter:string;search:string}){let startIso:string|null=null,endIso:string|null=null;if(startDateFilter){const[y,m,d]=startDateFilter.split("-").map(Number);startIso=new Date(y,m-1,d,0,0,0).toISOString()}if(endDateFilter){const[y,m,d]=endDateFilter.split("-").map(Number);endIso=new Date(y,m-1,d+1,0,0,0,0).toISOString()}let ids:(string|number)[]|null=null;if(search.trim()){const{data,error}=await supabase.from("drivers").select("id").or(`name.ilike.%${search.trim()}%,car_number.ilike.%${search.trim()}%,driver_id.ilike.%${search.trim()}%,license_number.ilike.%${search.trim()}%`);if(error)return{Все:0,Допущен:0,Ожидание:0,"Не допущен":0,"Явиться":0};ids=(data||[]).map((d:any)=>d.id);if(!ids.length)return{Все:0,Допущен:0,Ожидание:0,"Не допущен":0,"Явиться":0}}const get=async(status:string|null)=>{let q=supabase.from("inspections").select("id",{count:"exact",head:true});if(["Допущен","Не допущен","Явиться"].includes(status||"")){q=q.eq("overall_status",status!);if(startIso)q=q.gte("completed_at",startIso);if(endIso)q=q.lt("completed_at",endIso)}else if(status==="Ожидание"){q=q.eq("overall_status","Ожидание");if(startIso)q=q.gte("requested_at",startIso);if(endIso)q=q.lt("requested_at",endIso)}else if(startIso&&endIso)q=q.or(`and(completed_at.gte."${startIso}",completed_at.lt."${endIso}"),and(overall_status.eq.Ожидание,requested_at.gte."${startIso}",requested_at.lt."${endIso}")`);else if(startIso)q=q.or(`completed_at.gte."${startIso}",and(overall_status.eq.Ожидание,requested_at.gte."${startIso}")`);else if(endIso)q=q.or(`completed_at.lt."${endIso}",and(overall_status.eq.Ожидание,requested_at.lt."${endIso}")`);if(ids)q=q.in("driver_id",ids);const{count}=await q;return count??0};const[all,approved,pending,rejected,summon]=await Promise.all([get(null),get("Допущен"),get("Ожидание"),get("Не допущен"),get("Явиться")]);return{Все:all,Допущен:approved,Ожидание:pending,"Не допущен":rejected,"Явиться":summon}}
export async function fetchSingleInspection(recordId:string|number){const{data,error}=await supabase.from("inspections").select(baseSelect).eq("id",recordId).single();if(error||!data)return null;return formatInspectionItem(data,await getNames())}
export async function updateInspectionMedical(docId:string,now:string,alcoholVal:number,systolic:number|null,diastolic:number|null,drugIntoxication:boolean){const ok=alcoholVal===0&&!drugIntoxication&&isBloodPressureWithinNormalRange(systolic,diastolic);const names=await getConfiguredNames();const examinerId=getCurrentUserId();return supabase.from("inspections").update({medical_status:ok?"Допущен":"Не допущен",medical_date:now,breathalyzer_value:alcoholVal,blood_pressure_systolic:systolic,blood_pressure_diastolic:diastolic,drug_intoxication:drugIntoxication,medical_examiner_id:examinerId,medical_examiner_name:names.medic_surname}).eq("id",docId)}
export async function updateInspectionApprove(docId:string,now:string){const{data:current,error}=await supabase.from("inspections").select("blood_pressure_systolic,blood_pressure_diastolic,breathalyzer_value,drug_intoxication").eq("id",docId).single();if(error||!current)return{data:null,error:error??new Error("Не найдена запись осмотра")};let s=current.blood_pressure_systolic,d=current.blood_pressure_diastolic;if(s==null||d==null){s=120;d=80}const ok=isBloodPressureWithinNormalRange(s,d)&&(current.breathalyzer_value??0)===0&&current.drug_intoxication!==true;const names=await getConfiguredNames();const examinerId=getCurrentUserId();return supabase.from("inspections").update({overall_status:ok?"Допущен":"Не допущен",medical_status:ok?"Допущен":"Не допущен",mechanic_status:ok?"Допущен":"Не допущен",medical_date:now,mechanic_date:now,completed_at:now,breathalyzer_value:current.breathalyzer_value??0,blood_pressure_systolic:s,blood_pressure_diastolic:d,drug_intoxication:current.drug_intoxication===true,mechanic_issues:ok?[]:["Медицинские показатели не соответствуют норме"],medical_examiner_id:examinerId,mechanic_examiner_id:examinerId,medical_examiner_name:names.medic_surname,mechanic_examiner_name:names.mechanic_surname}).eq("id",docId)}
export async function updateInspectionReject(docId:string,now:string,_alcoholVal:number,issuesList:string[],_medStatus:string,_mechStatus:string,_overallStatus:string){const{data:current,error}=await supabase.from("inspections").select("medical_status").eq("id",docId).single();if(error||!current)return{data:null,error:error??new Error("Не найдена запись осмотра")};const mechStatus=issuesList.length?"Не допущен":"Допущен";const names=await getConfiguredNames();return supabase.from("inspections").update({overall_status:current.medical_status==="Допущен"&&mechStatus==="Допущен"?"Допущен":"Не допущен",mechanic_status:mechStatus,mechanic_date:now,completed_at:now,mechanic_issues:issuesList,mechanic_examiner_id:getCurrentUserId(),mechanic_examiner_name:names.mechanic_surname}).eq("id",docId)}
export async function updateInspectionReset(docId:string){return supabase.from("inspections").update({overall_status:"Ожидание",medical_status:"Ожидание",mechanic_status:"Ожидание",medical_date:null,mechanic_date:null,completed_at:null,breathalyzer_value:null,blood_pressure_systolic:null,blood_pressure_diastolic:null,drug_intoxication:false,mechanic_issues:[],medical_examiner_id:null,mechanic_examiner_id:null,medical_examiner_name:null,mechanic_examiner_name:null}).eq("id",docId)}
export async function deleteInspectionRecord(docId:string){return supabase.from("inspections").delete().eq("id",docId)}
export async function updateInspectionSummon(docId:string,_now:string){return supabase.from("inspections").update({overall_status:"Явиться",medical_status:"Явиться",mechanic_status:"Явиться",medical_date:null,mechanic_date:null,completed_at:null,breathalyzer_value:null,blood_pressure_systolic:null,blood_pressure_diastolic:null,drug_intoxication:false,mechanic_issues:[],medical_examiner_id:null,mechanic_examiner_id:null,medical_examiner_name:null,mechanic_examiner_name:null}).eq("id",docId)}
