/* eslint-disable @typescript-eslint/no-explicit-any */
import { supabase } from '@/lib/supabase';
import { fetchSystemSettings } from '@/services/settings.service';

export interface DriverData { id:number; driver_id:string; name:string; car_brand:string; car_number:string; license_number:string; license_expiry:string; medical_expiry:string; tech_inspection_expiry:string; insurance_expiry:string; customer_id:number; user_id?:number; customerName?:string; inspection_scope?:'medical'|'mechanic'|'both'; inspection_point_id?:number|null; }
const DRIVER_SELECT = `*, customers (name)`;

export const DriverDashboardService = {
  async getDriverByNumber(userLogin:string):Promise<DriverData|null>{let{data,error}=await supabase.from('drivers').select(DRIVER_SELECT).eq('driver_id',userLogin).maybeSingle();if(!data){const{data:userData}=await supabase.from('users').select('id').eq('login',userLogin).maybeSingle();if(userData?.id){const result=await supabase.from('drivers').select(DRIVER_SELECT).eq('user_id',userData.id).maybeSingle();data=result.data;error=result.error;}}if(error){console.error('Ошибка при запросе водителя:',error.message);return null;}if(!data)return null;return{...data,customerName:(data.customers as any)?.name||'Не указана',inspection_scope:data.inspection_scope||'both'};},
  subscribeToDriver(userLogin:string,onUpdate:(driver:DriverData|null)=>void){let active=true,refreshInFlight=false,refreshQueued=false;const refresh=async()=>{if(!active)return;if(refreshInFlight){refreshQueued=true;return;}refreshInFlight=true;try{const driver=await this.getDriverByNumber(userLogin);if(active)onUpdate(driver);}finally{refreshInFlight=false;if(active&&refreshQueued){refreshQueued=false;void refresh();}}};void refresh();const channel=supabase.channel(`driver-data-${userLogin}-${Date.now()}`).on('postgres_changes',{event:'*',schema:'public',table:'drivers'},()=>void refresh()).subscribe();const interval=window.setInterval(()=>void refresh(),30000);return()=>{active=false;window.clearInterval(interval);void supabase.removeChannel(channel);};},
  subscribeToChecks(driverDbId:number,onUpdate:(inspections:any[])=>void){let active=true,requestId=0,refreshInFlight=false,refreshQueued=false;const refresh=async()=>{if(!active)return;if(refreshInFlight){refreshQueued=true;return;}refreshInFlight=true;const currentRequest=++requestId;try{const{data,error}=await supabase.from('inspections').select(`*, inspection_points (id, name, address)`).eq('driver_id',driverDbId).order('requested_at',{ascending:false});if(error)console.error('Ошибка обновления осмотров:',error.message);else if(active&&currentRequest===requestId)onUpdate(data||[]);}finally{refreshInFlight=false;if(active&&refreshQueued){refreshQueued=false;void refresh();}}};void refresh();const channel=supabase.channel(`driver-inspections-${driverDbId}-${Date.now()}`).on('postgres_changes',{event:'*',schema:'public',table:'inspections',filter:`driver_id=eq.${driverDbId}`},()=>void refresh()).subscribe();const interval=window.setInterval(()=>void refresh(),30000);return()=>{active=false;requestId++;window.clearInterval(interval);void supabase.removeChannel(channel);};},
  subscribeToSettings(pointId:number|null|undefined,onUpdate:(settings:any)=>void){let active=true,refreshInFlight=false,refreshQueued=false;const refresh=async()=>{if(!active)return;if(refreshInFlight){refreshQueued=true;return;}refreshInFlight=true;try{const settings=await fetchSystemSettings(pointId);if(active)onUpdate(settings);}catch(error){console.error('Ошибка обновления настроек:',error);}finally{refreshInFlight=false;if(active&&refreshQueued){refreshQueued=false;void refresh();}}};void refresh();const channel=supabase.channel(`driver-system-settings-${pointId??'default'}-${Date.now()}`).on('postgres_changes',{event:'*',schema:'public',table:'inspection_points',filter:pointId?`id=eq.${pointId}`:undefined},()=>void refresh()).subscribe();const interval=window.setInterval(()=>void refresh(),30000);return()=>{active=false;window.clearInterval(interval);void supabase.removeChannel(channel);};},
  async acknowledgeSummon(inspectionId:number){const session=await fetch('/api/auth/session',{credentials:'include'}).then(r=>r.json());const driver=await this.getDriverByNumber(session?.session?.login||'');if(!driver)throw new Error('Водитель не найден');const response=await fetch('/api/driver/inspections/actions',{method:'POST',headers:{'Content-Type':'application/json'},credentials:'include',body:JSON.stringify({action:'acknowledge',driverDbId:driver.id,inspectionId})});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body?.error||'Не удалось подтвердить вызов');},
  async createInspection(driverDbId:number){const response=await fetch('/api/driver/inspections/actions',{method:'POST',headers:{'Content-Type':'application/json'},credentials:'include',body:JSON.stringify({action:'create',driverDbId})});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body?.error||'Не удалось создать запрос на осмотр');},
};
