/* eslint-disable react-hooks/set-state-in-effect */
/* eslint-disable @typescript-eslint/no-explicit-any */
"use client";

import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { AuthService } from "@/services/auth.service";
import { DriverDashboardService, DriverData } from "@/services/driver-dashboard.service";
import DriverHeader from "./components/DriverHeader";
import DriverCalendar from "./components/DriverCalendar";
import DriverActionBlock from "./components/DriverActionBlock";
import DriverHistory from "./components/DriverHistory";
import DriverSidebar from "./components/DriverSidebar";
import DriverWarnings, { DocWarning } from "./components/DriverWarnings";

const STATUS_STYLES: Record<string,string> = {
  Допущен:"bg-[#2F855A]/10 text-[#2F855A] border-[#2F855A]/20", Ожидание:"bg-amber-50 text-amber-700 border-amber-200",
  "Не допущен":"bg-[#C53030]/10 text-[#C53030] border-[#C53030]/20", Отстранен:"bg-[#C53030]/10 text-[#C53030] border-[#C53030]/20", Явиться:"bg-amber-50 text-amber-800 border-amber-200",
};
const getDisplayStatus=(status?:string,address?:string)=>status==="Допущен"?"Подтверждено":status==="Не допущен"?"Отклонено":status==="Явиться"?(address?`Необходимо явиться на пункт предрейсового осмотра по адресу: ${address}`:"Необходимо явиться на пункт предрейсового осмотра по адресу, указанному администратором"):status||"Ожидание";

export default function DriverPage(){
  const router=useRouter(); const [driver,setDriver]=useState<DriverData|null>(null); const [loadingDriver,setLoadingDriver]=useState(true);
  const [isSubmitting,setIsSubmitting]=useState(false); const [latestCheck,setLatestCheck]=useState<any>(null); const [timeRemaining,setTimeRemaining]=useState<number|null>(null);
  const [selectedDateChecks,setSelectedDateChecks]=useState<any[]>([]); const [monthChecks,setMonthChecks]=useState<Record<string,number>>({}); const [allChecks,setAllChecks]=useState<any[]>([]);
  const [isMobileMenuOpen,setIsMobileMenuOpen]=useState(false); const [summonCheck,setSummonCheck]=useState<any>(null); const [inspectionAddress,setInspectionAddress]=useState("");
  const today=useMemo(()=>new Date(),[]); const [selectedDate,setSelectedDate]=useState(today); const [viewDate,setViewDate]=useState(new Date(today.getFullYear(),today.getMonth(),1));
  const scope=String((driver as any)?.inspection_scope||"both").toLowerCase(); const hasMedical=scope==="both"||scope==="medical"; const hasMechanic=scope==="both"||scope==="mechanic";
  const iso=(date:Date)=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}-${String(date.getDate()).padStart(2,"0")}`;
  const parseDate=(value:any):Date|null=>{if(!value)return null;if(value instanceof Date)return value;const str=String(value).trim();if(/^\d{2}\.\d{2}\.\d{4}/.test(str)){const [day,month,year]=str.split(/[.\s:]/);return new Date(Number(year),Number(month)-1,Number(day));}const date=new Date(str);return Number.isNaN(date.getTime())?null:date;};
  const daysLeft=(value:any)=>{const date=parseDate(value);if(!date)return null;const a=new Date(today.getFullYear(),today.getMonth(),today.getDate()).getTime();const b=new Date(date.getFullYear(),date.getMonth(),date.getDate()).getTime();return Math.ceil((b-a)/86400000);};
  const currentWarnings=useMemo<DocWarning[]>(()=>{if(!driver)return [];const docs=[["Водительское удостоверение",driver.license_expiry],["Медицинская справка",driver.medical_expiry],["Техосмотр",driver.tech_inspection_expiry],["Страховка",driver.insurance_expiry]] as const;return docs.flatMap(([name,value])=>{const left=daysLeft(value);return left!==null&&left<=3?[{name,date:String(value),daysLeft:left,expired:left<0}]:[];});},[driver]);
  const hasExpiredDocs=currentWarnings.some(w=>w.expired);
  const completionTime=(check:any)=>{if(check.completed_at)return new Date(check.completed_at).getTime();const values=[hasMedical&&check.medical_date?new Date(check.medical_date).getTime():0,hasMechanic&&check.mechanic_date?new Date(check.mechanic_date).getTime():0];const max=Math.max(...values);return max>0?max:new Date(check.requested_at||check.created_at).getTime();};

  useEffect(()=>{const login=AuthService.getSession()?.login;if(!login){setLoadingDriver(false);return;}let active=true;DriverDashboardService.getDriverByNumber(login).then(data=>{if(active)setDriver(data);}).catch(e=>console.error("Ошибка загрузки водителя:",e)).finally(()=>{if(active)setLoadingDriver(false);});const unsubscribe=DriverDashboardService.subscribeToDriver(0,login,data=>{if(active)setDriver(data);});return()=>{active=false;unsubscribe();};},[]);
  useEffect(()=>{if(!driver)return;const unsubscribe=DriverDashboardService.subscribeToChecks(driver.id,inspections=>{setAllChecks(inspections);});return unsubscribe;},[driver?.id]);
  useEffect(()=>{const unsubscribe=DriverDashboardService.subscribeToSettings(settings=>{setInspectionAddress(String(settings.organization_address||"").trim());});return unsubscribe;},[]);
  useEffect(()=>{const target=iso(selectedDate);const selected=allChecks.filter(check=>iso(new Date(check.requested_at||check.created_at))===target).sort((a,b)=>new Date(b.requested_at||b.created_at).getTime()-new Date(a.requested_at||a.created_at).getTime());const counts:Record<string,number>={};let latest:any=null;let maxTime=0;let summon:any=null;for(const check of allChecks){const date=new Date(check.requested_at||check.created_at);const key=iso(date);counts[key]=(counts[key]||0)+1;if(date.getTime()>maxTime){maxTime=date.getTime();latest=check;}if(check.summon===true&&!check.summon_acknowledged)summon=check;}setSelectedDateChecks(selected);setMonthChecks(counts);setLatestCheck(latest);setSummonCheck(summon);},[allChecks,selectedDate]);
  useEffect(()=>{if(!latestCheck){setTimeRemaining(0);return;}if(latestCheck.overall_status==="Ожидание"||latestCheck.overall_status==="Явиться"){setTimeRemaining(null);return;}const update=()=>{const left=12*60*60*1000-(Date.now()-completionTime(latestCheck));setTimeRemaining(left>0?left:0);};update();const timer=window.setInterval(update,60000);return()=>window.clearInterval(timer);},[latestCheck,hasMedical,hasMechanic]);
  const requestInspection=async()=>{if(!driver||hasExpiredDocs||timeRemaining!==0)return;setIsSubmitting(true);try{await DriverDashboardService.createInspection(driver.id);}catch(error){console.error("Ошибка при отправке запроса:",error);alert("Произошла ошибка при отправке запроса. Пожалуйста, попробуйте снова.");}finally{setIsSubmitting(false);}};
  const sameDay=(a:Date,b:Date)=>a.getFullYear()===b.getFullYear()&&a.getMonth()===b.getMonth()&&a.getDate()===b.getDate(); const dateTime=(v?:string)=>v?new Date(v).toLocaleString("ru-RU",{day:"2-digit",month:"2-digit",year:"numeric",hour:"2-digit",minute:"2-digit"}):"—"; const time=(v?:string)=>v?new Date(v).toLocaleTimeString("ru-RU",{hour:"2-digit",minute:"2-digit"}):""; const statusDot=(status?:string)=>{const s=(status||"").toLowerCase().trim();if(s==="допущен")return"bg-[#2F855A]";if(s==="отстранен"||s==="не допущен")return"bg-[#C53030]";if(s==="ожидание"||s==="явиться")return"bg-amber-500";return"bg-slate-300";}; const selectedLabel=selectedDate.toLocaleDateString("ru-RU",{day:"numeric",month:"long",year:"numeric"});
  const handleLogout=()=>{AuthService.logout();router.push("/login");}; const handleAcknowledgeSummon=async(id:number)=>{try{await DriverDashboardService.acknowledgeSummon(id);setSummonCheck(null);}catch(error){console.error("Ошибка подтверждения вызова:",error);}};
  if(loadingDriver)return <div className="flex min-h-screen items-center justify-center bg-slate-50"><div className="text-center text-slate-500"><div className="mx-auto mb-3 h-8 w-8 animate-spin rounded-full border-2 border-slate-300 border-t-[#042433]"/><p className="text-sm">Загрузка данных водителя...</p></div></div>;
  if(!driver)return <div className="flex min-h-screen items-center justify-center bg-slate-50 p-4"><div className="max-w-sm text-center"><div className="mx-auto mb-4 grid h-16 w-16 place-items-center rounded-full bg-[#C53030]/10 text-[#C53030]"><span className="text-2xl">!</span></div><h2 className="text-lg font-bold">Водитель не найден</h2><p className="mt-2 text-sm text-slate-500">Запись водителя отсутствует в Supabase.</p><button onClick={handleLogout} className="mt-4 rounded-lg bg-[#042433] px-4 py-2 text-sm font-medium text-white">Вернуться к входу</button></div></div>;
  return <div className="min-h-screen bg-slate-50 text-slate-900"><DriverHeader onMenuOpen={()=>setIsMobileMenuOpen(true)} onLogout={handleLogout}/><main className="relative mx-auto max-w-5xl space-y-5 p-4 md:p-6"><div><h2 className="text-2xl font-bold tracking-tight">{driver.name}</h2><p className="mt-1 text-sm text-slate-500">{driver.customerName} · Таб. № <span className="font-mono font-medium">{driver.driver_id}</span></p></div>{summonCheck&&<div className="flex items-start gap-3 rounded-xl border border-amber-200 bg-amber-50 p-4 shadow-sm"><span className="mt-0.5 text-amber-600">!</span><div className="flex-1"><p className="text-sm font-semibold text-amber-800">Вас вызывают на пункт предрейсового осмотра</p><p className="mt-0.5 text-xs text-amber-700">{inspectionAddress?`Необходимо явиться по адресу: ${inspectionAddress}`:"Администратор запросил ваше явление на пункт предрейсового осмотра."}</p><button onClick={()=>handleAcknowledgeSummon(summonCheck.id)} className="mt-3 rounded-lg bg-amber-200 px-3 py-1.5 text-xs font-medium text-amber-900 hover:bg-amber-300">Понятно</button></div></div>}<DriverWarnings driver={driver} warnings={currentWarnings}/><div className="grid grid-cols-1 gap-4 md:grid-cols-3"><DriverSidebar driver={driver} isOpen={isMobileMenuOpen} onClose={()=>setIsMobileMenuOpen(false)} daysLeft={daysLeft}/><div className="space-y-4 md:col-span-2"><DriverCalendar viewDate={viewDate} selectedDate={selectedDate} today={today} monthChecks={monthChecks} onDateSelect={setSelectedDate} onPrev={()=>setViewDate(new Date(viewDate.getFullYear(),viewDate.getMonth()-1,1))} onNext={()=>setViewDate(new Date(viewDate.getFullYear(),viewDate.getMonth()+1,1))}/>{sameDay(selectedDate,today)&&<DriverActionBlock latestCheck={latestCheck} inspectionAddress={inspectionAddress} statusStyles={STATUS_STYLES} getDisplayStatus={getDisplayStatus} hasExpiredDocs={hasExpiredDocs} timeRemaining={timeRemaining} isSubmitting={isSubmitting} onRequest={requestInspection}/>}<DriverHistory checks={selectedDateChecks} hasMedical={hasMedical} hasMechanic={hasMechanic} selectedLabel={selectedLabel} statusStyles={STATUS_STYLES} getDisplayStatus={getDisplayStatus} inspectionAddress={inspectionAddress} statusDot={statusDot} dateTime={dateTime} time={time}/></div></div></main></div>;
}
