/* eslint-disable @typescript-eslint/no-explicit-any */
"use client";

import { Building2, Calendar, FileText, Car, Stethoscope, Wrench, Wine, Check as CheckIcon, X, RotateCcw, Trash2, Bell } from "lucide-react";
import { Inspection } from "../../../../../types/database.types";

interface CheckRowProps { item: Inspection; onApprove: (docId: string) => void; onReject: (docId: string) => void; onResetStatus: (docId: string) => void; onDelete: (check: Inspection) => void; onCustomerClick?: (customer: string) => void; onSummon?: (item: Inspection) => void; }

export function CheckRow({ item, onApprove, onReject, onResetStatus, onDelete, onCustomerClick, onSummon }: CheckRowProps) {
  const statusStr = item.status as string;
  const isApproved = statusStr === "Допущен";
  const isWaiting = statusStr === "Ожидание";
  const hasBloodPressure = item.bloodPressureSystolic != null && item.bloodPressureDiastolic != null;
  const getStatusBadge = (status: string) => status === "Допущен" ? "bg-emerald-50 text-emerald-700 border-emerald-200" : status === "Не допущен" ? "bg-rose-50 text-rose-700 border-rose-200" : status === "Явиться" ? "bg-amber-100 text-amber-800 border-amber-300" : "bg-amber-50 text-amber-700 border-amber-200";

  return (
    <tr className={`group transition-all hover:bg-slate-50/80 ${isApproved ? "bg-emerald-50/20" : ""}`}>
      <td className="px-4 py-4 text-center align-middle"><span className="inline-flex items-center justify-center rounded-md bg-slate-100 px-2 py-1 font-mono text-xs font-semibold text-slate-700 shadow-sm">№{item.id}</span></td>
      <td className="px-4 py-4 align-middle"><div className="font-semibold text-slate-900">{item.driver}</div><button type="button" className="mt-1 inline-flex max-w-full cursor-pointer items-center gap-1.5 text-left text-xs font-medium text-slate-500 transition-colors hover:text-[#042433] focus:outline-none disabled:cursor-default" onClick={() => onCustomerClick?.(item.customer)} disabled={!onCustomerClick}><Building2 size={12} className="shrink-0 text-slate-400" /><span className="truncate">{item.customer}</span></button><div className="mt-1 flex items-center gap-1.5 text-[11px] text-slate-400"><Calendar size={12} />{item.date}</div></td>
      <td className="px-4 py-4 align-middle"><div className="flex flex-col gap-2"><div className="flex items-center gap-2 text-xs text-slate-700"><FileText size={14} className="shrink-0 text-slate-400" /><span>ВУ: <span className="font-semibold text-slate-900">{item.documents.license}</span></span><span className="text-slate-300">|</span><span className="text-slate-500">до {item.documents.licenseExpires}</span></div><div className="flex flex-wrap items-center gap-2 text-xs"><div className="flex items-center gap-1.5 rounded-md border border-slate-200 bg-white px-2 py-0.5 shadow-sm"><Car size={13} className="text-slate-400" /><span className="font-mono font-medium tracking-wide text-slate-800">{item.car.number}</span><span className="text-slate-400">•</span><span className="text-slate-600">{item.car.brand}</span></div><div className="flex items-center gap-2 text-[11px] text-slate-500"><span className="rounded bg-slate-100 px-1.5 py-0.5">Мед: {item.documents.medical}</span><span className="rounded bg-slate-100 px-1.5 py-0.5">ТО: {item.documents.inspection}</span></div></div></div></td>
      <td className="px-4 py-4 align-middle">
        <div className="grid min-w-0 grid-cols-2 gap-3">
          <div className="min-w-0 overflow-hidden rounded-lg border border-slate-100 bg-white p-2.5 shadow-sm">
            <div className="flex min-w-0 items-start gap-2"><div className="rounded-md bg-teal-50 p-1 text-teal-700"><Stethoscope size={14} /></div><div className="min-w-0 flex-1"><div className="truncate text-xs font-medium text-slate-800">{item.medic}</div><div className="text-[10px] text-slate-400">{item.medicTime}</div></div></div>
            {item.medicTime !== "—" && <div className="mt-2 flex min-w-0 items-center gap-1 rounded-md bg-slate-50 px-2 py-1.5 text-[10px] leading-4">
              {hasBloodPressure && <span className="flex min-w-0 flex-1 items-center gap-1 whitespace-nowrap"><Stethoscope size={11} className="shrink-0 text-teal-600" /><span className="truncate text-slate-500">АД</span><strong className="shrink-0 text-slate-900">{item.bloodPressureSystolic}/{item.bloodPressureDiastolic}</strong></span>}
              <span className="shrink-0 text-slate-300">·</span>
              <span className="flex shrink-0 items-center gap-1 whitespace-nowrap"><Wine size={11} className="text-rose-500" /><span className="text-slate-500">Алк.</span><strong className="text-slate-900">{item.alcohol ?? "0.0"}</strong></span>
            </div>}
          </div>
          <div className="min-w-0 overflow-hidden rounded-lg border border-slate-100 bg-white p-2.5 shadow-sm"><div className="flex min-w-0 items-start gap-2"><div className="rounded-md bg-amber-50 p-1 text-amber-700"><Wrench size={14} /></div><div className="min-w-0 flex-1"><div className="truncate text-xs font-medium text-slate-800">{item.mechanic}</div><div className="text-[10px] text-slate-400">{item.mechanicTime}</div></div></div>{item.mechanicTime !== "—" && <div className="mt-2 rounded bg-slate-50 px-2 py-1 text-[11px] text-slate-500">{item.mechanicReasons && item.mechanicReasons.length > 0 ? <span className="font-medium text-rose-600">{item.mechanicReasons.join(", ")}</span> : <span className="font-medium text-emerald-600">Без замечаний</span>}</div>}</div>
        </div>
      </td>
      <td className="px-4 py-4 text-center align-middle"><div className="flex flex-col items-center gap-2"><span className={`inline-flex items-center rounded-full border px-3 py-1 text-xs font-semibold shadow-sm ${getStatusBadge(item.status)}`}>{item.status}</span><div className="mt-1 flex w-full flex-col items-stretch gap-1.5">{isWaiting ? <><button type="button" onClick={() => onApprove(item.docId)} className="flex cursor-pointer items-center justify-center gap-1.5 rounded-lg bg-[#2F855A] px-2 py-2 text-xs font-medium text-white shadow-sm transition-colors hover:bg-[#276749]"><CheckIcon size={14} /> Допустить</button><button type="button" onClick={() => onReject(item.docId)} className="flex w-full cursor-pointer items-center justify-center gap-1.5 whitespace-nowrap rounded-lg bg-[#C53030] px-2 py-2 text-xs font-medium text-white shadow-md transition-all hover:bg-[#9B2C2C] hover:shadow-lg active:scale-95"><X size={14} /> Не допустить</button><button type="button" onClick={() => onSummon?.(item)} className="flex cursor-pointer items-center justify-center gap-1.5 rounded-lg border border-amber-200 bg-amber-50 px-2 py-2 text-xs font-medium text-amber-700 shadow-sm transition-colors hover:bg-amber-100"><Bell size={14} /> Явиться</button></> : <><button type="button" onClick={() => onResetStatus(item.docId)} className="flex cursor-pointer items-center justify-center gap-1.5 rounded-lg border border-amber-300 bg-amber-50 px-2 py-2 text-xs font-medium text-amber-800 shadow-sm transition-colors hover:bg-amber-100"><RotateCcw size={14} /> В ожидание</button><button type="button" onClick={() => onDelete(item)} className="flex cursor-pointer items-center justify-center gap-1.5 rounded-lg border border-[#C53030]/20 bg-[#C53030]/5 px-2 py-2 text-xs font-medium text-[#C53030] shadow-sm transition-colors hover:bg-[#C53030]/10"><Trash2 size={14} /> Удалить</button></>}</div></div></td>
    </tr>
  );
}