/* eslint-disable @typescript-eslint/no-explicit-any */
"use client";

import { Building2, Calendar, FileText, Car, Stethoscope, Wrench, Wine, Check as CheckIcon, X, RotateCcw, Trash2, Bell } from "lucide-react";
import { Inspection } from "../../../../../types/database.types";

interface CheckCardProps { item: Inspection; onApprove: (docId: string) => void; onReject: (docId: string) => void; onResetStatus: (docId: string) => void; onDelete: (check: Inspection) => void; onCustomerClick?: (customer: string) => void; onSummon?: (item: Inspection) => void; }

export function CheckCard({ item, onApprove, onReject, onResetStatus, onDelete, onCustomerClick, onSummon }: CheckCardProps) {
  const statusStr = item.status as string;
  const isApproved = statusStr === "Допущен";
  const isWaiting = statusStr === "Ожидание";
  const hasBloodPressure = item.bloodPressureSystolic != null && item.bloodPressureDiastolic != null;

  const getStatusBadge = (status: string) => {
    switch (status) {
      case "Допущен": return "bg-emerald-50 text-emerald-700 border-emerald-200";
      case "Не допущен": return "bg-rose-50 text-rose-700 border-rose-200";
      case "Явиться": return "bg-amber-100 text-amber-800 border-amber-300";
      default: return "bg-amber-50 text-amber-700 border-amber-200";
    }
  };

  return (
    <div className={`overflow-hidden rounded-2xl border border-slate-200/80 bg-white p-4 shadow-[0_2px_10px_rgba(15,23,42,0.04)] transition-shadow hover:shadow-[0_6px_24px_rgba(15,23,42,0.07)] sm:p-5 ${isApproved ? "border-emerald-200 bg-emerald-50/20" : ""}`}>
      <div className="flex items-center justify-between border-b border-slate-100 pb-3.5"><div className="flex items-center gap-2"><span className="inline-flex items-center justify-center rounded-lg border border-slate-200 bg-slate-50 px-2.5 py-1.5 font-mono text-xs font-semibold text-slate-700">№{item.id}</span><span className="flex items-center gap-1 text-xs text-slate-500"><Calendar size={12}/>{item.date}</span></div><span className={`inline-flex items-center rounded-full border px-2.5 py-0.5 text-xs font-semibold shadow-sm ${getStatusBadge(item.status)}`}>{item.status}</span></div>
      <div className="py-4"><div className="font-semibold leading-5 text-slate-950">{item.driver}</div><button type="button" className="mt-1 inline-flex max-w-full cursor-pointer items-center gap-1.5 text-left text-xs font-medium text-slate-500 hover:text-[#042433]" onClick={() => onCustomerClick?.(item.customer)} disabled={!onCustomerClick}><Building2 size={12} className="shrink-0 text-slate-400"/><span className="truncate">{item.customer}</span></button></div>
      <div className="space-y-2.5 border-t border-slate-100 py-4 text-xs text-slate-700"><div className="flex items-center justify-between"><div className="flex items-center gap-2 text-slate-600"><FileText size={14} className="text-slate-400"/><span>ВУ: <strong className="text-slate-900">{item.documents.license}</strong></span></div><span className="text-[11px] text-slate-400">до {item.documents.licenseExpires}</span></div><div className="flex flex-wrap items-center justify-between gap-2 rounded-xl border border-slate-200/80 bg-slate-50/60 p-2.5"><div className="flex items-center gap-1.5"><Car size={13} className="text-slate-400"/><span className="font-mono font-medium text-slate-800">{item.car.number}</span><span className="text-slate-400">•</span><span className="text-slate-600">{item.car.brand}</span></div><div className="flex gap-2 text-[10px] text-slate-500"><span>Мед: {item.documents.medical}</span><span>ТО: {item.documents.inspection}</span></div></div></div>
      <div className="grid grid-cols-2 gap-2 border-t border-slate-100 pt-3">
        <div className="flex flex-col justify-between rounded-xl border border-slate-200/80 bg-slate-50/60 p-2.5 text-xs"><div className="flex items-start gap-1.5"><div className="rounded bg-teal-50 p-1 text-teal-700"><Stethoscope size={13}/></div><div className="min-w-0 flex-1"><div className="truncate font-medium text-slate-800">{item.medic}</div><div className="text-[10px] text-slate-400">{item.medicTime}</div></div></div>{item.medicTime !== "—" && <div className="mt-2 flex min-w-0 items-center gap-3 rounded bg-white px-2 py-1.5 text-[10px]"><span className="inline-flex items-center gap-1 whitespace-nowrap text-slate-600"><span className="text-[12px]">🩺</span><span>Давление</span><strong className="text-slate-900">{hasBloodPressure ? `${item.bloodPressureSystolic}/${item.bloodPressureDiastolic}` : "—"}</strong></span><span className="h-3 w-px bg-slate-200"/><span className="inline-flex items-center gap-1 whitespace-nowrap"><Wine size={12} className="text-rose-500"/><span className="text-slate-500">Алк.</span><strong className="text-slate-900">{item.alcohol ?? "0.0"}</strong></span></div>}</div>
        <div className="flex flex-col justify-between rounded-xl border border-slate-200/80 bg-slate-50/60 p-2.5 text-xs"><div className="flex items-start gap-1.5"><div className="rounded bg-amber-50 p-1 text-amber-700"><Wrench size={13}/></div><div className="min-w-0 flex-1"><div className="truncate font-medium text-slate-800">{item.mechanic}</div><div className="text-[10px] text-slate-400">{item.mechanicTime}</div></div></div>{item.mechanicTime !== "—" && <div className="mt-2 rounded bg-white px-1.5 py-0.5 text-[10px]">{item.mechanicReasons && item.mechanicReasons.length > 0 ? <span className="font-medium text-rose-600">{item.mechanicReasons.join(", ")}</span> : <span className="font-medium text-emerald-600">Без замечаний</span>}</div>}</div>
      </div>
      <div className="mt-4 flex flex-col items-stretch gap-2 border-t border-slate-100 pt-4">{isWaiting ? <><div className="grid grid-cols-2 gap-2"><button type="button" onClick={() => onApprove(item.docId)} className="flex cursor-pointer items-center justify-center gap-1 rounded-xl bg-emerald-600 px-2.5 py-2.5 text-xs font-semibold text-white hover:bg-emerald-700"><CheckIcon size={14}/>Допустить</button><button type="button" onClick={() => onReject(item.docId)} className="flex cursor-pointer items-center justify-center gap-1 whitespace-nowrap rounded-xl bg-rose-600 px-2.5 py-2.5 text-xs font-semibold text-white hover:bg-rose-700"><X size={14}/>Не допустить</button></div><button type="button" onClick={() => onSummon?.(item)} className="flex cursor-pointer items-center justify-center gap-1.5 rounded-xl border border-amber-200 bg-amber-50 px-2.5 py-2.5 text-xs font-semibold text-amber-700 hover:bg-amber-100"><Bell size={14}/>Явиться</button></> : <><button type="button" onClick={() => onResetStatus(item.docId)} className="flex cursor-pointer items-center justify-center gap-1.5 rounded-xl border border-amber-200 bg-amber-50 px-2.5 py-2.5 text-xs font-semibold text-amber-800 hover:bg-amber-100"><RotateCcw size={14}/>В ожидание</button><button type="button" onClick={() => onDelete(item)} className="flex cursor-pointer items-center justify-center gap-1.5 rounded-xl border border-rose-200 bg-rose-50 px-2.5 py-2.5 text-xs font-semibold text-rose-700 hover:bg-rose-100"><Trash2 size={14}/>Удалить</button></>}</div>
    </div>
  );
}