"use client";

import { useEffect, useMemo, useState } from "react";
import { CalendarDays, CheckCircle2, Clock3, X, XCircle } from "lucide-react";
import type { DatabaseInspection, Driver } from "@/types/database.types";
import { fetchDriverInspectionHistory } from "@/services/driver-history.service";

interface Props { isOpen: boolean; driver: Driver | null; onClose: () => void; }
function toDateInput(date: Date) { return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}-${String(date.getDate()).padStart(2,"0")}`; }
function formatDateTime(value: string | null | undefined) { if (!value) return "—"; const date = new Date(value); return Number.isNaN(date.getTime()) ? "—" : date.toLocaleString("ru-RU", { day:"2-digit", month:"2-digit", year:"numeric", hour:"2-digit", minute:"2-digit" }); }
function statusMeta(status: string | null) {
  if (status === "Допущен") return { wrap:"border-emerald-100 bg-emerald-50/50", badge:"border-emerald-200 bg-emerald-50 text-emerald-700", icon:<CheckCircle2 size={13}/>, label:"Допущен" };
  if (status === "Не допущен") return { wrap:"border-rose-100 bg-rose-50/45", badge:"border-rose-200 bg-rose-50 text-rose-700", icon:<XCircle size={13}/>, label:"Не допущен" };
  if (status === "Явиться") return { wrap:"border-amber-100 bg-amber-50/45", badge:"border-amber-200 bg-amber-50 text-amber-700", icon:<Clock3 size={13}/>, label:"Явиться" };
  return { wrap:"border-slate-200 bg-white", badge:"border-slate-200 bg-slate-50 text-slate-600", icon:<Clock3 size={13}/>, label:status || "Без статуса" };
}
function inspectionReasons(item: DatabaseInspection) { const reasons=[...(item.mechanic_issues||[])]; if(item.drug_intoxication) reasons.push("Наркотическое опьянение"); if(item.breathalyzer_value!==null&&item.breathalyzer_value>0) reasons.push(`Алкоголь: ${item.breathalyzer_value.toFixed(2)}‰`); return reasons; }

export default function DriverHistoryModal({ isOpen, driver, onClose }: Props) {
  const today=useMemo(()=>new Date(),[]); const [startDate,setStartDate]=useState(toDateInput(new Date(today.getFullYear(),today.getMonth(),1))); const [endDate,setEndDate]=useState(toDateInput(today)); const [items,setItems]=useState<DatabaseInspection[]>([]); const [loading,setLoading]=useState(false); const [error,setError]=useState<string|null>(null);
  useEffect(()=>{if(!isOpen)return;setStartDate(toDateInput(new Date(today.getFullYear(),today.getMonth(),1)));setEndDate(toDateInput(today));},[isOpen,today]);
  useEffect(()=>{if(!isOpen||!driver)return;if(startDate>endDate){setItems([]);setError("Дата начала не может быть позже даты окончания.");return;}let cancelled=false;setLoading(true);setError(null);fetchDriverInspectionHistory(driver.id,startDate,endDate).then(({data,error:e})=>{if(cancelled)return;setItems(data);setError(e?.message||null);setLoading(false);});return()=>{cancelled=true;};},[isOpen,driver,startDate,endDate]);
  if(!isOpen||!driver)return null;
  const setPeriod=(type:"today"|"week"|"month")=>{const now=new Date();if(type==="today"){const v=toDateInput(now);setStartDate(v);setEndDate(v);}else if(type==="week"){const day=now.getDay()||7;const monday=new Date(now);monday.setDate(now.getDate()-day+1);const sunday=new Date(monday);sunday.setDate(monday.getDate()+6);setStartDate(toDateInput(monday));setEndDate(toDateInput(sunday));}else{setStartDate(toDateInput(new Date(now.getFullYear(),now.getMonth(),1)));setEndDate(toDateInput(new Date(now.getFullYear(),now.getMonth()+1,0)));}};
  const stats={total:items.length,allowed:items.filter(x=>x.overall_status==="Допущен").length,rejected:items.filter(x=>x.overall_status==="Не допущен").length,appear:items.filter(x=>x.overall_status==="Явиться").length};
  return <div className="fixed inset-0 z-[60] flex items-center justify-center bg-slate-900/50 p-3 backdrop-blur-sm" onClick={onClose}><div className="flex max-h-[94vh] w-full max-w-5xl flex-col overflow-hidden rounded-xl border border-slate-200 bg-white shadow-2xl" onClick={e=>e.stopPropagation()}>
    <header className="border-b border-slate-100 px-5 py-3"><div className="flex items-center justify-between gap-4"><div className="min-w-0"><div className="flex flex-wrap items-center gap-x-5 gap-y-1 text-sm"><div className="truncate"><span className="font-medium text-slate-400">Водитель:</span> <span className="font-semibold text-slate-900">{driver.name||"Без имени"}</span></div><div className="truncate"><span className="font-medium text-slate-400">Заказчик:</span> <span className="font-semibold text-slate-700">{driver.customer?.name||"Без заказчика"}</span></div><span className="rounded-md bg-slate-100 px-2 py-0.5 font-mono text-xs font-semibold text-slate-600">№{driver.driver_id||driver.id}</span></div><div className="mt-1 text-xs text-slate-400">История осмотров</div></div><button type="button" onClick={onClose} className="shrink-0 rounded-lg p-1.5 text-slate-400 transition hover:bg-slate-100 hover:text-slate-700"><X size={18}/></button></div></header>
    <section className="border-b border-slate-100 bg-slate-50/60 px-5 py-2.5"><div className="flex flex-wrap items-center justify-between gap-2"><div className="flex flex-wrap gap-1.5"><button type="button" onClick={()=>setPeriod("today")} className="rounded-md border border-slate-200 bg-white px-2.5 py-1.5 text-xs font-medium text-slate-600 hover:bg-slate-50">Сегодня</button><button type="button" onClick={()=>setPeriod("week")} className="rounded-md border border-slate-200 bg-white px-2.5 py-1.5 text-xs font-medium text-slate-600 hover:bg-slate-50">7 дней</button><button type="button" onClick={()=>setPeriod("month")} className="rounded-md bg-[#042433] px-2.5 py-1.5 text-xs font-medium text-white hover:bg-[#031d29]">Месяц</button></div><div className="flex items-center gap-2"><label className="text-[10px] font-medium text-slate-500">С<input type="date" value={startDate} onChange={e=>setStartDate(e.target.value)} className="ml-1 rounded-md border border-slate-300 bg-white px-2 py-1.5 text-xs text-slate-700 outline-none focus:border-[#042433]"/></label><span className="mt-3 text-slate-300">→</span><label className="text-[10px] font-medium text-slate-500">По<input type="date" value={endDate} onChange={e=>setEndDate(e.target.value)} className="ml-1 rounded-md border border-slate-300 bg-white px-2 py-1.5 text-xs text-slate-700 outline-none focus:border-[#042433]"/></label></div></div></section>
    {!loading&&!error&&<section className="grid grid-cols-4 gap-1.5 border-b border-slate-100 px-5 py-2.5"><div className="rounded-lg border border-slate-200 bg-white px-3 py-2"><div className="text-[10px] text-slate-400">Всего</div><div className="text-base font-semibold text-slate-900">{stats.total}</div></div><div className="rounded-lg border border-emerald-100 bg-emerald-50/40 px-3 py-2"><div className="text-[10px] text-emerald-600">Допущен</div><div className="text-base font-semibold text-emerald-700">{stats.allowed}</div></div><div className="rounded-lg border border-rose-100 bg-rose-50/40 px-3 py-2"><div className="text-[10px] text-rose-600">Не допущен</div><div className="text-base font-semibold text-rose-700">{stats.rejected}</div></div><div className="rounded-lg border border-amber-100 bg-amber-50/40 px-3 py-2"><div className="text-[10px] text-amber-600">Явиться</div><div className="text-base font-semibold text-amber-700">{stats.appear}</div></div></section>}
    <main className="min-h-0 flex-1 overflow-y-auto bg-slate-50/30 px-5 py-3">{loading?<div className="flex min-h-40 items-center justify-center text-sm text-slate-400">Загрузка истории...</div>:error?<div className="rounded-lg border border-rose-100 bg-rose-50 p-3 text-sm text-rose-700">{error}</div>:items.length===0?<div className="flex min-h-40 flex-col items-center justify-center text-center"><CalendarDays size={26} className="mb-2 text-slate-300"/><p className="text-sm font-medium text-slate-700">За выбранный период прохождений нет</p><p className="mt-1 text-xs text-slate-400">Попробуйте выбрать другой период.</p></div>:<div className="space-y-1.5">{items.map(item=>{const meta=statusMeta(item.overall_status);const pressure=item.blood_pressure_systolic!==null&&item.blood_pressure_diastolic!==null?`${item.blood_pressure_systolic}/${item.blood_pressure_diastolic}`:null;const reasons=inspectionReasons(item);const showMedical=item.overall_status!=="Явиться";return <article key={item.id} className={`rounded-lg border px-3 py-2 ${meta.wrap}`}><div className="flex flex-col gap-2 xl:flex-row xl:items-center xl:justify-between"><div className="flex min-w-0 flex-wrap items-center gap-x-3 gap-y-1"><span className="text-xs font-semibold text-slate-900">{formatDateTime(item.requested_at)}</span><span className={`inline-flex items-center gap-1 rounded-full border px-2 py-0.5 text-[10px] font-semibold ${meta.badge}`}>{meta.icon}{meta.label}</span>{showMedical&&<><span className="text-[11px] text-slate-500">Медик: <b className="text-slate-700">{item.medical_status||"—"}</b></span>{pressure&&<span className="font-mono text-[11px] font-semibold text-slate-700">АД {pressure}</span>}<span className="text-[11px] text-slate-500">Алк: <b className="font-mono text-slate-700">{item.breathalyzer_value===null?"—":`${item.breathalyzer_value.toFixed(2)}‰`}</b></span><span className="text-[11px] text-slate-500">Нарк.: <b className={item.drug_intoxication?"text-rose-600":"text-emerald-600"}>{item.drug_intoxication?"Да":"Нет"}</b></span><span className="text-[11px] text-slate-500">Механик: <b className="text-slate-700">{item.mechanic_status||"—"}</b></span></>}{!showMedical&&<span className="text-[11px] text-amber-700">Показания и отметки отсутствуют</span>}</div>{reasons.length>0&&item.overall_status!=="Явиться"&&<div className="shrink-0 text-[10px] text-slate-500 xl:max-w-[35%] xl:text-right"><span className="font-semibold">Причины:</span> {reasons.join(" · ")}</div>}</div></article>})}</div>}</main>
    <footer className="flex items-center justify-end border-t border-slate-100 bg-white px-5 py-2"><button type="button" onClick={onClose} className="rounded-md px-3 py-1.5 text-xs font-medium text-slate-500 hover:bg-slate-100 hover:text-slate-700">Закрыть</button></footer>
  </div></div>;
}