-- Inspection points are independent operational locations.
-- Keep organization-level data in system_settings; move point-specific
-- address/specialist/pricing data to this table.

create table if not exists public.inspection_points (
  id bigint generated by default as identity primary key,
  name text not null,
  address text not null default '',
  medic_last_name text not null default '',
  mechanic_last_name text not null default '',
  medical_inspection_price numeric(12,2) not null default 0.90,
  mechanic_inspection_price numeric(12,2) not null default 0.90,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into public.inspection_points (id, name, address, medic_last_name, mechanic_last_name, medical_inspection_price, mechanic_inspection_price)
select
  1,
  'Пункт №1',
  coalesce(s.organization_address, ''),
  coalesce(s.medic_last_name, ''),
  coalesce(s.mechanic_last_name, ''),
  coalesce(s.medical_inspection_price, 0.90),
  coalesce(s.mechanic_inspection_price, 0.90)
from public.system_settings s
where s.id = 1
  and not exists (select 1 from public.inspection_points where id = 1);

insert into public.inspection_points (id, name)
select 2, 'Пункт №2'
where not exists (select 1 from public.inspection_points where id = 2);

alter table public.users add column if not exists inspection_point_id bigint references public.inspection_points(id);
alter table public.drivers add column if not exists inspection_point_id bigint references public.inspection_points(id);
alter table public.inspections add column if not exists inspection_point_id bigint references public.inspection_points(id);

update public.users set inspection_point_id = 1 where role = 'admin' and inspection_point_id is null;
update public.drivers set inspection_point_id = 1 where inspection_point_id is null;
update public.inspections i
set inspection_point_id = d.inspection_point_id
from public.drivers d
where d.id = i.driver_id and i.inspection_point_id is null;

alter table public.inspection_points alter column id restart with 3;

create index if not exists idx_users_inspection_point on public.users(inspection_point_id);
create index if not exists idx_drivers_inspection_point on public.drivers(inspection_point_id);
create index if not exists idx_inspections_inspection_point on public.inspections(inspection_point_id);

-- Keep new inspection rows attached to the driver's point.
create or replace function public.set_inspection_point_from_driver()
returns trigger
language plpgsql
as $$
begin
  if new.inspection_point_id is null then
    select d.inspection_point_id into new.inspection_point_id
    from public.drivers d
    where d.id = new.driver_id;
  end if;
  return new;
end;
$$;

drop trigger if exists trg_set_inspection_point_from_driver on public.inspections;
create trigger trg_set_inspection_point_from_driver
before insert on public.inspections
for each row execute function public.set_inspection_point_from_driver();

-- IMPORTANT: assign the second administrator to point 2 after creating them:
-- update public.users set inspection_point_id = 2 where id = <ADMIN_2_ID>;
