-- Inspection points are independent operational locations.
-- Point-specific address, specialists and pricing live here.
-- Which point an administrator works with is stored on users.inspection_point_id.

create table if not exists public.inspection_points (
  id bigint generated by default as identity primary key,
  name text not null,
  address text not null default '',
  medic_surname text not null default '',
  mechanic_surname text not null default '',
  medical_exam_price numeric(12,2) not null default 0.90,
  mechanic_exam_price numeric(12,2) not null default 0.90,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Existing databases may have received an earlier version of this migration.
-- Keep the actual application column names stable.
alter table public.inspection_points add column if not exists medic_surname text not null default '';
alter table public.inspection_points add column if not exists mechanic_surname text not null default '';
alter table public.inspection_points add column if not exists medical_exam_price numeric(12,2) not null default 0.90;
alter table public.inspection_points add column if not exists mechanic_exam_price numeric(12,2) not null default 0.90;
alter table public.inspection_points add column if not exists updated_at timestamptz not null default now();

insert into public.inspection_points (
  id, name, address, medic_surname, mechanic_surname,
  medical_exam_price, mechanic_exam_price
)
select
  1,
  'Пункт осмотра №1',
  coalesce(s.organization_address, ''),
  coalesce(s.medic_surname, ''),
  coalesce(s.mechanic_surname, ''),
  coalesce(s.medical_exam_price, 0.90),
  coalesce(s.mechanic_exam_price, 0.90)
from public.system_settings s
where s.id = 1
  and not exists (select 1 from public.inspection_points where id = 1);

insert into public.inspection_points (id, name)
select 2, 'Пункт осмотра №2'
where not exists (select 1 from public.inspection_points where id = 2);

alter table public.users add column if not exists inspection_point_id bigint references public.inspection_points(id);
alter table public.drivers add column if not exists inspection_point_id bigint references public.inspection_points(id);
alter table public.inspections add column if not exists inspection_point_id bigint references public.inspection_points(id);

-- Existing administrators get a point only when one has not been assigned yet.
update public.users
set inspection_point_id = 1
where role = 'admin' and inspection_point_id is null;

-- Do NOT assign new inspections from the driver's point. A driver can visit
-- any point; the point is selected when an administrator accepts the inspection.
-- Existing inspection_point_id values are intentionally preserved as history.

alter table public.inspection_points alter column id restart with 3;

create index if not exists idx_users_inspection_point on public.users(inspection_point_id);
create index if not exists idx_drivers_inspection_point on public.drivers(inspection_point_id);
create index if not exists idx_inspections_inspection_point on public.inspections(inspection_point_id);

-- Remove the old trigger which incorrectly inherited the driver's point.
drop trigger if exists trg_set_inspection_point_from_driver on public.inspections;
drop function if exists public.set_inspection_point_from_driver();

-- IMPORTANT:
-- Assign point 2 directly to administrator #2 in users:
-- update public.users set inspection_point_id = 2 where id = <ADMIN_2_ID>;
